apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/products:latest
          ports:
            - containerPort: 8080
